#!/bin/bash

set -x

set -eo pipefail

# Check for pip environment variables and generate a distutils.cfg if
# one does not already exist, setting equivalent settings for
# easy_install. We need to check for distutils.cfg in the /tmp/src
# directory as the original assemble script hasn't been run yet so
# source files have not been copied into place yet. The /tmp/src
# directory is copied into /opt/app-root/src which is also $HOME so
# distutils.cfg will be found. We still generate distutils.cfg into
# /tmp/src though so that if the base Python S2I builder images start
# implementing this, our version takes precedence to make sure it works
# how we expect it to for now.

if [ ! -f /tmp/src/distutils.cfg ]; then
    if [ x"$PIP_NO_INDEX" = x"true" ]; then
        cat >> /tmp/distutils.cfg << !
allowed_hosts = None
!
    fi

    if [ x"$PIP_INDEX_URL" != x"" ]; then
        cat >> /tmp/distutils.cfg << !
index_url = $PIP_INDEX_URL
!
    fi

    if [ x"$PIP_FIND_LINKS" != x"" ]; then
        cat >> /tmp/distutils.cfg << !
find_links = $PIP_FIND_LINKS
!
    fi

    if [ -f /tmp/distutils.cfg ]; then
        cat > /tmp/src/distutils.cfg << !
[easy_install]
!

        cat /tmp/distutils.cfg >> /tmp/src/distutils.cfg

        rm /tmp/distutils.cfg
    fi
fi

# Exec the original assemble script.

exec /usr/libexec/s2i/assemble
