#!/bin/bash

# If PIP_INDEX_URL is specified, generate a distutils.cfg if one does
# not already exist, setting index_url so that easy_install uses the
# same package index. We need to check for distutils.cfg in the /tmp/src
# directory as the original assemble script hasn't been run yet so
# source files have not been copied into place yet. The /tmp/src
# directory is copied into /opt/app-root/src which is also $HOME so
# distutils.cfg will be found. We still generate distutils.cfg into
# /tmp/src though so that if the base Python S2I builder images start
# implementing this, our version takes precedence to make sure it works
# how we expect it to.

if [ ! -f /tmp/src/distutils.cfg ]; then
    cat > /tmp/src/distutils.cfg < !
[easy_install]
!

    if [ x"$PIP_INDEX_URL" != x"" ]; then
        cat >> /tmp/src/distutils.cfg < !
index_url = $PIP_INDEX_URL
!
    fi

    if [ x"$PIP_FIND_LINKS" != x"" ]; then
        cat >> /tmp/src/distutils.cfg < !
find_links = $PIP_FIND_LINKS
!
    fi
fi

# Exec the original assemble script.

exec /usr/libexec/s2i/assemble
